name: Generate Register Files

# Controls when the workflow will run
on:
  issue_comment:
      types: [created]

env:
  MSDK_DIR: msdk
  MSDK-INTERNAL_DIR: msdk-internal

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Generate register files job.
  generate-on-pr:
    # Run on branches, not forked PR branches
    if: |
      contains(github.event.comment.body, '/generate-register-files')

    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Command Dispatch
        uses: actions/github-script@v6
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }

            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)

            try {
              const result = await github.rest.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      
      - name: Checkout msdk internal repository
        uses: actions/checkout@v3
        with:
          repository: ADI-MSDK-Workflow-Test/msdk-internal
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          path: ${{ env.MSDK-INTERNAL_DIR }}
      
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          fetch-depth: 0
          script: |
            core.info(`Comment: ${github.event.comment.body}`)

      - name: Generating register files.
        run: |
          pwd
          ls
          cd ../${{ env.MSDK-INTERNAL_DIR }}/SVD/Devices/
